### ISSUE TITLE
react-native@0.65.1  WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.

### ISSUE THREAD

**Issue by zongjiang-gh** [react-native-clipboard/clipboard#116]
Appeared in `react-native 0.65.1` Android development:

WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.

It can be fixed like this https://github.com/invertase/react-native-firebase/pull/5616/files#diff-c887076b0c80d540aed1bfbb472cc8f20516634e8e72d53014c65d690bba4fb1

**Comment by klandell** [comment]
I'm seeing this too after updating React Native.

**Comment by GuillaumeHemmen** [comment]
I have the same issue with iOS with ``new NativeEventEmitter()` requires a non-null argument`.

**Comment by cristianoccazinsp** [comment]
Should be resolved with https://github.com/react-native-clipboard/clipboard/pull/113

**Comment by LPitonakova** [comment]
Hi, I still have the same issue, and I just installed "@react-native-clipboard/clipboard": "^1.9.0", . I am on RN 0.65.1

**Comment by adamtsai1** [comment]
I've just encountered this issue. I am on RN 0.68.2.

**Comment by jailandrade** [comment]
I'm also using RN 0.68.2 and I've found this error after installing this library

**Comment by derochedesign** [comment]
Those on 0.68.2, did you manage to fix the issue? Or did upgrading RN fix it?

**Comment by mharrison-nzme** [comment]
Experiencing this issue on RN 0.67.4

**Comment by chrisglein** [comment]
> Should be resolved with #113

This would have only affected the Android version, right? And people are seeing this on iOS and Windows. So this needs a deeper fix. Has anyone attempted the style of fix [listed above](https://github.com/invertase/react-native-firebase/pull/5616/files#diff-c887076b0c80d540aed1bfbb472cc8f20516634e8e72d53014c65d690bba4fb1)? If I can get that to work I'll submit a PR, but so far I haven't gotten it yet.

**Comment by thongle12** [comment]
Hi,
For whom still confront this issue: I found the way here
just simply cd ios and pod install 
then start your project again
Hope this helps!

**Comment by espipj** [comment]
I believe this is still an issue

**Comment by chrisglein** [comment]
> I believe this is still an issue

Yes it is, for iOS. There has been a fix made for Android and Windows, but iOS needs a similar fix if anyone wants to make a PR.

**Comment by mertcankose** [comment]
error still persists

**Comment by chrisglein** [comment]
> error still persists

On which platform?

**Comment by mertcankose** [comment]
> > error still persists
> 
> On which platform?

Oh sorry, I started ios simulator again. It solved.
